"""Assemble the final single-file bundle: a flattened, dependency-free ``.py``."""

from __future__ import annotations

import hashlib
from pathlib import Path

from . import flatten as _flatten
from .discovery import Module


def _prepend_globals(body: str, global_vars: dict[str, str], prefix: str) -> str:
    """Prepend a ``name = value`` block for ``global_vars`` to ``body`` — but keep any leading
    ``from __future__`` imports first (PEP 236 requires them to be the first statements).
    ``prefix`` (e.g. the bundle header, or "") is placed at the very top.
    """
    vars_block = "\n".join(f"{name} = {value}" for name, value in global_vars.items())
    future_prefix = ""
    remaining = body
    for line in body.splitlines(keepends=True):
        if line.startswith("from __future__"):
            future_prefix += line
            remaining = remaining[len(line):]
        else:
            break
    if future_prefix:
        return prefix + future_prefix + "\n" + vars_block + "\n\n" + remaining
    return prefix + vars_block + "\n\n" + body


def assemble(
    payload_path: Path,
    modules: list[Module],
    sources: dict[str, str],
    payload_source: str,
    *,
    order: list[str],
    minified: bool,
    treeshaken: bool,
    compression_passes: list[str] | None = None,
    strip_comments: bool = False,
    global_vars: dict[str, str] | None = None,
) -> tuple[str, list[str]]:
    """Produce the full text of the output ``.py`` plus any flatten warnings.

    Vendored modules are inlined as real top-level source (see :mod:`bundler.flatten`);
    there is no runtime loader, no embedded strings, and no disk access at run time.
    """
    body, warnings = _flatten.flatten(
        modules, sources, payload_source, order, payload_path.name,
        strip_comments=strip_comments,
    )

    if strip_comments:
        if global_vars:
            return _prepend_globals(body, global_vars, ""), warnings
        return body, warnings

    # Deterministic content fingerprint (no timestamps -> reproducible output).
    digest = hashlib.sha256()
    for module in modules:
        digest.update(module.name.encode())
        digest.update(b"\0")
        digest.update(sources[module.name].encode("utf-8"))
        digest.update(b"\0")
    digest.update(payload_source.encode("utf-8"))
    fingerprint = digest.hexdigest()[:16]

    flags = list(compression_passes or [])
    if treeshaken:
        flags.append("experimental-treeshake")
    if minified:
        flags.append("minify")
    flag_str = ", ".join(flags) if flags else "none"

    header = (
        "#!/usr/bin/env python3\n"
        "# -*- coding: utf-8 -*-\n"
        "#\n"
        "# Flattened single-file bundle generated by bundler. DO NOT EDIT.\n"
        f"# payload: {payload_path.name}\n"
        f"# inlined modules: {len(modules)}\n"
        f"# passes: {flag_str}\n"
        f"# fingerprint: {fingerprint}\n"
        "#\n"
        "# Vendored modules are inlined as plain top-level code -- no loader, no\n"
        "# embedded strings, no runtime file access. Runs on stock Python 3.\n"
        "#\n"
    )

    if global_vars:
        # PEP 236: __future__ imports must be the first statements — _prepend_globals re-hoists
        # them above the injected vars_block, keeping the header at the very top.
        return _prepend_globals(body, global_vars, header + "\n"), warnings

    return header + "\n" + body, warnings
